import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { GatewayProvider } from "@/lib/gateway/context";
import { ThemeProvider } from "@/lib/theme/context";
import { getThemeBootstrapScript } from "@/lib/theme/engine";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const bootstrapScript = getThemeBootstrapScript();

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <head>
        <script dangerouslySetInnerHTML={{ __html: bootstrapScript }} />
      </head>
      <body className="min-h-full flex flex-col">
        <GatewayProvider>
          <ThemeProvider>{children}</ThemeProvider>
        </GatewayProvider>
      </body>
    </html>
  );
}
